version: '3'

services:
  wordpress:
    build: ./wordpress/
    depends_on:
      - mariadb
    container_name: wordpress
    ports: 
      - 9000
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - deez
      - mynet
    
  nginx:
    build: ./nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - mynet
    links:
      - mariadb
  mariadb:
    build: database/
    container_name: mariadb
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - deez
volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/obouadel/Desktop/Inception/wp_volume
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/obouadel/Desktop/Inception/db_volume

networks:
  mynet:
  deez: {"driver": "bridge"}